# Generated by Django 5.0.1 on 2024-01-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='desciption',
            new_name='description',
        ),
    ]
